name:                snake
version:             0.1.0.0
github:              "will-clarke/snake"
license:             BSD3
author:              "William Clarke"
maintainer:          "wmmclarke@gmail.com"
copyright:           "2019 William Clarke"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/will-clarke/snake#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty
- hspec
- QuickCheck
- microlens
- random

library:
  source-dirs: src

executables:
  snake-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snake

tests:
  snake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snake
