* Snake written in Haskell

No idea if this will ever work... at the moment we've got some basic stuff showing on a terminal :|

*** How to run

    - Make sure you've got [[https://www.haskellstack.org/][stack]] installed. Then:
#+BEGIN_SRC sh
git clone https://github.com/will-clarke/snake-haskell
cd snake-haskell
stack run
#+END_SRC    


Some notes about how I'm implementing this:
- Worth having two typeclasses - ~Tickable~ & ~Drawable~?

#+BEGIN_SRC haskell
class Drawable a where
    coords :: [Coordinates]
    icon :: Char  
  
class Tickable a where
    tick :: a - > a
#+END_SRC
No idea if this is a good idea... We'll find out I guess... ¯\_(ツ)_/¯

- [ ] Find out how to get screen dimensions from Brick. This could be tricky / monad-y
- [ ] Add attributes to make it pretty
- [X] Don't allow snakes to turn on 180 degrees
- [X] Allow Food to be eatable
- [X] Make food increment the score
- [ ] Start snake moving left to right or something
- [X] Reseed food after it's eaten
- [ ] command line -- pass in initial seed. Optparse-applicative. Maybe different game modes (eg. just left-right)
- [ ] loading screen!
- [X] remove keypress
- [ ] rename model
- [ ] implement pausing / resuming
- [ ] Make the game faster as you eat more fruit
- [ ] move stdgen into food
- [ ] make it so you can't move further from the boundary
- [ ] add an endgame screen
- [ ] add a pre-game screen
- [ ] high scores stored locally?
- [ ] high scores stored on a server somewhere?????
- [ ] record a list of all the keystrokes??? We could even replay this later on....
- [X] allow seed to be passed in & CLI args used


